### ISSUE TITLE
Downloads becomes corrupt and the plugin cannot be loaded

### ISSUE THREAD

**Issue by jaime29010** [InventivetalentDev/SpigetUpdater#2]
The downloaded jar cannot be loaded by bukkit, is there any way to fix this?
Here is a stacktrace of the exception thrown at runtime
```
[12:07:05 ERROR]: Could not load 'plugins\CombatActionBar.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `me.jaime29010.combatactionbar.Main'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:540) [spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: me.jaime29010.combatactionbar.Main
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_101]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_101]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        ... 7 more
Caused by: java.io.IOException: invalid header field name: Manifest*Version
        at java.util.jar.Attributes.read(Unknown Source) ~[?:1.8.0_101]
        at java.util.jar.Manifest.read(Unknown Source) ~[?:1.8.0_101]
        at java.util.jar.Manifest.<init>(Unknown Source) ~[?:1.8.0_101]
        at java.util.jar.JarFile.getManifestFromReference(Unknown Source) ~[?:1.8.0_101]
        at java.util.jar.JarFile.getManifest(Unknown Source) ~[?:1.8.0_101]
        at sun.misc.URLClassPath$JarLoader$2.getManifest(Unknown Source) ~[?:1.8.0_101]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_101]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_101]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_101]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_101]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot_server.jar:git-Spigot-cf6dea3-ca1bb1c]
        ... 7 more
```

**Comment by InventivetalentDev** [comment]
Please try downloading the file manually from https://api.spiget.org/v2/resources/<your resource id>/download and check if it's still corrupted.

**Comment by InventivetalentDev** [comment]
Nevermind, should be fixed now. The download script didn't properly close the connection, so it downloaded additional data.
(https://github.com/SpiGetOrg/RestAPI/commit/02b7a6303ddf4cec07aebb8bfdc34eb345d14ea3)
