### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by Flynrod** [InventivetalentDev/SpigetUpdater#5]
Hello,

I have a small problem with the updater : 
`java.io.FileNotFoundException: http://api.spiget.org/v2/resources/38865?ut=1496861000391
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_131]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_131]
        at be.flynrod.featherspawn.utils.Updater$1.run(Updater.java:63) [FeatherSpawn.jar:?]
        at be.flynrod.featherspawn.utils.CheckUpdate$1.dispatch(CheckUpdate.java:13) [FeatherSpawn.jar:?]
        at be.flynrod.featherspawn.utils.Updater.checkForUpdate(Updater.java:57) [FeatherSpawn.jar:?]
        at be.flynrod.featherspawn.utils.CheckUpdate.check(CheckUpdate.java:16) [FeatherSpawn.jar:?]
        at be.flynrod.featherspawn.Manager.initialize(Manager.java:43) [FeatherSpawn.jar:?]
        at be.flynrod.featherspawn.FeatherSpawn.onEnable(FeatherSpawn.java:68) [FeatherSpawn.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

Screenshot: [https://image.prntscr.com/image/a90a6ebb3d314e08804cb5bbbd67ff9f.png](url)

**Comment by InventivetalentDev** [comment]
`FileNotFoundException` means that you're trying to reach an endpoint which isn't available. If you open the URL from the beginning of your stack trace, you will get a `404: Not Found` error in your browser. 

Looking at your resource's page, I've noticed that it's a paid resource, which unfortunately isn't supported by Spiget. Sorry about that.

**Comment by Flynrod** [comment]
Ok, thank you very much for the reply. I will try to find an alternative. 👍
